#!/usr/bin/env bash


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

source "$DIR/../contrib/copied-cvc4-env.sh"

webget \
  "https://www.antlr3.org/download/antlr-3.4-complete.jar" \
  "./antlr-3.4-complete.jar"
