macro(switch_add_btor_test name)
  add_executable(${name} "${PROJECT_SOURCE_DIR}/tests/btor/${name}.cpp")
  target_link_libraries(${name} PRIVATE test-solvers)
  target_link_libraries(${name} PRIVATE GTest::gtest_main)
  add_test(NAME ${name}_test COMMAND ${name})
endmacro()

switch_add_btor_test(btor-array-empty-assignment)
switch_add_btor_test(btor-array-models)
switch_add_btor_test(btor-const-arrays)
switch_add_btor_test(btor-data-structures)
switch_add_btor_test(btor-exceptions)
switch_add_btor_test(btor-incremental)
switch_add_btor_test(btor-indexed-op-tests)
switch_add_btor_test(btor-negation)
switch_add_btor_test(btor-opts)
switch_add_btor_test(btor-reset)
switch_add_btor_test(btor-simple)
switch_add_btor_test(btor-substitute)
switch_add_btor_test(btor-tests)
switch_add_btor_test(btor-transfer)
